spring.application.name=implementacion

# IMPORTANTE: Reconoce HTTPS detrás de AWS API Gateway
server.forward-headers-strategy=framework

# Credenciales fijas para Spring Security
spring.security.user.name=${SECURITY_USER:admin}
spring.security.user.password=${SECURITY_PASSWORD:admin123}

db.ms1=${DB_MS1:db_ms1}
db.ms2=${DB_MS2:db_ms2}
db.ms3=${DB_MS3:db_ms3}
db.ms4=${DB_MS4:db_ms4}
aws.athena.output-location=${ATHENA_OUTPUT_LOCATION:s3://ingesta/}

# Cambia la ruta interna donde se genera el JSON de OpenAPI
springdoc.api-docs.path=/ms5/api/analytics/docs
springdoc.swagger-ui.path=/ms5/api/analytics/swagger-ui.html

# (Opcional) Forzar el servidor HTTPS en Swagger
springdoc.servers[0].url=https://qjxnz9uqv9.execute-api.us-east-1.amazonaws.com
springdoc.servers[0].description=AWS API Gateway HTTPS
