spring.application.name=implementacion

# Credenciales fijas para Spring Security
spring.security.user.name=${SECURITY_USER:admin}
spring.security.user.password=${SECURITY_PASSWORD:admin123}

db.ms1=${DB_MS1:db_ms1}
db.ms2=${DB_MS2:db_ms2}
db.ms3=${DB_MS3:db_ms3}
db.ms4=${DB_MS4:db_ms4}
aws.athena.output-location=${ATHENA_OUTPUT_LOCATION:s3://ingesta/}

# Cambia la ruta interna donde se genera el JSON de OpenAPI (obligatorio para que no choque)
springdoc.api-docs.path=/ms5/api/analytics/docs
